apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-myworkspace-deployment
spec:
  selector:
    matchLabels:
      app: hello-myworkspace
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-myworkspace
    spec:
        containers:
        - name: hello-myworkspace
          image: udayalingam/hello-from-myworkspace:latest
          ports:
          - containerPort: 5000
            protocol: TCP
        imagePullSecrets:
        - name: regcred