apiVersion: v1
kind: Service
metadata:
  name: hello-myworkspace-service
spec:
  selector:
    app: hello-myworkspace-deployment
  ports:
  - name: http
    protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer